//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService {
    using System.Runtime.Serialization;
using System;


[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseEntrada", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Entrada")]
[System.SerializableAttribute()]
public partial class BaseEntrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
{

	[System.NonSerializedAttribute()]
	private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int EmpresaField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int EmpresaSHFCodField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int FilialField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int MatriculaField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string UsuarioAlteracaoField;

	[global::System.ComponentModel.BrowsableAttribute(false)]
	public System.Runtime.Serialization.ExtensionDataObject ExtensionData
	{
		get
		{
			return this.extensionDataField;
		}
		set
		{
			this.extensionDataField = value;
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Empresa
	{
		get
		{
			return this.EmpresaField;
		}
		set
		{
			if ((this.EmpresaField.Equals(value) != true))
			{
				this.EmpresaField = value;
				this.RaisePropertyChanged("Empresa");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int EmpresaSHFCod
	{
		get
		{
			return this.EmpresaSHFCodField;
		}
		set
		{
			if ((this.EmpresaSHFCodField.Equals(value) != true))
			{
				this.EmpresaSHFCodField = value;
				this.RaisePropertyChanged("EmpresaSHFCod");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Filial
	{
		get
		{
			return this.FilialField;
		}
		set
		{
			if ((this.FilialField.Equals(value) != true))
			{
				this.FilialField = value;
				this.RaisePropertyChanged("Filial");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Matricula
	{
		get
		{
			return this.MatriculaField;
		}
		set
		{
			if ((this.MatriculaField.Equals(value) != true))
			{
				this.MatriculaField = value;
				this.RaisePropertyChanged("Matricula");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string UsuarioAlteracao
	{
		get
		{
			return this.UsuarioAlteracaoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.UsuarioAlteracaoField, value) != true))
			{
				this.UsuarioAlteracaoField = value;
				this.RaisePropertyChanged("UsuarioAlteracao");
			}
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetorno", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioJCxYsfas))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFotoFuncionarioJCxYsfas))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioEmailJCxYsfas))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioCompletoJCxYsfas))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioPostoDeTrabalhoJCxYsfas))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioPostoDeTrabalhoJCxYsfas))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioAutoCompletJCxYsfas))]
public partial class BaseRetorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
{

	[System.NonSerializedAttribute()]
	private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private bool ResultadoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string RetornoMensagemField;

	[global::System.ComponentModel.BrowsableAttribute(false)]
	public System.Runtime.Serialization.ExtensionDataObject ExtensionData
	{
		get
		{
			return this.extensionDataField;
		}
		set
		{
			this.extensionDataField = value;
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public bool Resultado
	{
		get
		{
			return this.ResultadoField;
		}
		set
		{
			if ((this.ResultadoField.Equals(value) != true))
			{
				this.ResultadoField = value;
				this.RaisePropertyChanged("Resultado");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string RetornoMensagem
	{
		get
		{
			return this.RetornoMensagemField;
		}
		set
		{
			if ((object.ReferenceEquals(this.RetornoMensagemField, value) != true))
			{
				this.RetornoMensagemField = value;
				this.RaisePropertyChanged("RetornoMensagem");
			}
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetornoObjetoOfFuncionarioSumarioJCxYsfas", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
public partial class BaseRetornoObjetoOfFuncionarioSumarioJCxYsfas : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumario ObjetoField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumario Objeto
	{
		get
		{
			return this.ObjetoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ObjetoField, value) != true))
			{
				this.ObjetoField = value;
				this.RaisePropertyChanged("Objeto");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
public partial class BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumario[] ObjetoField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumario[] Objeto
	{
		get
		{
			return this.ObjetoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ObjetoField, value) != true))
			{
				this.ObjetoField = value;
				this.RaisePropertyChanged("Objeto");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetornoObjetoOfFotoFuncionarioJCxYsfas", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
public partial class BaseRetornoObjetoOfFotoFuncionarioJCxYsfas : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FotoFuncionario ObjetoField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FotoFuncionario Objeto
	{
		get
		{
			return this.ObjetoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ObjetoField, value) != true))
			{
				this.ObjetoField = value;
				this.RaisePropertyChanged("Objeto");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetornoObjetoOfFuncionarioEmailJCxYsfas", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
public partial class BaseRetornoObjetoOfFuncionarioEmailJCxYsfas : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioEmail ObjetoField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioEmail Objeto
	{
		get
		{
			return this.ObjetoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ObjetoField, value) != true))
			{
				this.ObjetoField = value;
				this.RaisePropertyChanged("Objeto");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetornoObjetoOfFuncionarioSumarioCompletoJCxYsfas", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
public partial class BaseRetornoObjetoOfFuncionarioSumarioCompletoJCxYsfas : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumarioCompleto ObjetoField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumarioCompleto Objeto
	{
		get
		{
			return this.ObjetoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ObjetoField, value) != true))
			{
				this.ObjetoField = value;
				this.RaisePropertyChanged("Objeto");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetornoObjetoOfFuncionarioPostoDeTrabalhoJCxYsfas", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
public partial class BaseRetornoObjetoOfFuncionarioPostoDeTrabalhoJCxYsfas : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioPostoDeTrabalho ObjetoField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioPostoDeTrabalho Objeto
	{
		get
		{
			return this.ObjetoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ObjetoField, value) != true))
			{
				this.ObjetoField = value;
				this.RaisePropertyChanged("Objeto");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetornoObjetoListOfFuncionarioPostoDeTrabalhoJCxYsfas", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
public partial class BaseRetornoObjetoListOfFuncionarioPostoDeTrabalhoJCxYsfas : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioPostoDeTrabalho[] ObjetoField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioPostoDeTrabalho[] Objeto
	{
		get
		{
			return this.ObjetoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ObjetoField, value) != true))
			{
				this.ObjetoField = value;
				this.RaisePropertyChanged("Objeto");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "BaseRetornoObjetoListOfFuncionarioAutoCompletJCxYsfas", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.SharedKernel.Base.Retorno")]
[System.SerializableAttribute()]
public partial class BaseRetornoObjetoListOfFuncionarioAutoCompletJCxYsfas : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioAutoComplet[] ObjetoField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioAutoComplet[] Objeto
	{
		get
		{
			return this.ObjetoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ObjetoField, value) != true))
			{
				this.ObjetoField = value;
				this.RaisePropertyChanged("Objeto");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "FuncionarioAutoComplet", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.QueryModel.DTO.Funcionario")]
[System.SerializableAttribute()]
public partial class FuncionarioAutoComplet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
{

	[System.NonSerializedAttribute()]
	private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int MatriculaField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string NomeField;

	[global::System.ComponentModel.BrowsableAttribute(false)]
	public System.Runtime.Serialization.ExtensionDataObject ExtensionData
	{
		get
		{
			return this.extensionDataField;
		}
		set
		{
			this.extensionDataField = value;
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Matricula
	{
		get
		{
			return this.MatriculaField;
		}
		set
		{
			if ((this.MatriculaField.Equals(value) != true))
			{
				this.MatriculaField = value;
				this.RaisePropertyChanged("Matricula");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Nome
	{
		get
		{
			return this.NomeField;
		}
		set
		{
			if ((object.ReferenceEquals(this.NomeField, value) != true))
			{
				this.NomeField = value;
				this.RaisePropertyChanged("Nome");
			}
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "FuncionarioSumario", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.QueryModel.DTO.Funcionario")]
[System.SerializableAttribute()]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumarioCompleto))]
public partial class FuncionarioSumario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
{

	[System.NonSerializedAttribute()]
	private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private bool AtivoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string CpfField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int EmpresaField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int FilialField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int MatriculaField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string NomeField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int TerceiroField;

	[global::System.ComponentModel.BrowsableAttribute(false)]
	public System.Runtime.Serialization.ExtensionDataObject ExtensionData
	{
		get
		{
			return this.extensionDataField;
		}
		set
		{
			this.extensionDataField = value;
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public bool Ativo
	{
		get
		{
			return this.AtivoField;
		}
		set
		{
			if ((this.AtivoField.Equals(value) != true))
			{
				this.AtivoField = value;
				this.RaisePropertyChanged("Ativo");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Cpf
	{
		get
		{
			return this.CpfField;
		}
		set
		{
			if ((object.ReferenceEquals(this.CpfField, value) != true))
			{
				this.CpfField = value;
				this.RaisePropertyChanged("Cpf");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Empresa
	{
		get
		{
			return this.EmpresaField;
		}
		set
		{
			if ((this.EmpresaField.Equals(value) != true))
			{
				this.EmpresaField = value;
				this.RaisePropertyChanged("Empresa");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Filial
	{
		get
		{
			return this.FilialField;
		}
		set
		{
			if ((this.FilialField.Equals(value) != true))
			{
				this.FilialField = value;
				this.RaisePropertyChanged("Filial");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Matricula
	{
		get
		{
			return this.MatriculaField;
		}
		set
		{
			if ((this.MatriculaField.Equals(value) != true))
			{
				this.MatriculaField = value;
				this.RaisePropertyChanged("Matricula");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Nome
	{
		get
		{
			return this.NomeField;
		}
		set
		{
			if ((object.ReferenceEquals(this.NomeField, value) != true))
			{
				this.NomeField = value;
				this.RaisePropertyChanged("Nome");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Terceiro
	{
		get
		{
			return this.TerceiroField;
		}
		set
		{
			if ((this.TerceiroField.Equals(value) != true))
			{
				this.TerceiroField = value;
				this.RaisePropertyChanged("Terceiro");
			}
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "FuncionarioSumarioCompleto", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.QueryModel.DTO.Funcionario")]
[System.SerializableAttribute()]
public partial class FuncionarioSumarioCompleto : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumario
{

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string BairroField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string CEPField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string CargoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string CidadeNomeField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string ComplementoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string ConjugeField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private System.DateTime DataIngressoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private System.DateTime DataNascimentoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string[] EmailsField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int EstadoCivilCodField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string EstadoCivilDescricaoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string EstadoSiglaField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string LogradouroField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string NecessidadeEspecialField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string NomeMaeField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string NomePaiField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string NumeroField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string RgField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string SexoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.TelefoneSumario[] TelefonesField;

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Bairro
	{
		get
		{
			return this.BairroField;
		}
		set
		{
			if ((object.ReferenceEquals(this.BairroField, value) != true))
			{
				this.BairroField = value;
				this.RaisePropertyChanged("Bairro");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string CEP
	{
		get
		{
			return this.CEPField;
		}
		set
		{
			if ((object.ReferenceEquals(this.CEPField, value) != true))
			{
				this.CEPField = value;
				this.RaisePropertyChanged("CEP");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Cargo
	{
		get
		{
			return this.CargoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.CargoField, value) != true))
			{
				this.CargoField = value;
				this.RaisePropertyChanged("Cargo");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string CidadeNome
	{
		get
		{
			return this.CidadeNomeField;
		}
		set
		{
			if ((object.ReferenceEquals(this.CidadeNomeField, value) != true))
			{
				this.CidadeNomeField = value;
				this.RaisePropertyChanged("CidadeNome");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Complemento
	{
		get
		{
			return this.ComplementoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ComplementoField, value) != true))
			{
				this.ComplementoField = value;
				this.RaisePropertyChanged("Complemento");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Conjuge
	{
		get
		{
			return this.ConjugeField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ConjugeField, value) != true))
			{
				this.ConjugeField = value;
				this.RaisePropertyChanged("Conjuge");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public System.DateTime DataIngresso
	{
		get
		{
			return this.DataIngressoField;
		}
		set
		{
			if ((this.DataIngressoField.Equals(value) != true))
			{
				this.DataIngressoField = value;
				this.RaisePropertyChanged("DataIngresso");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public System.DateTime DataNascimento
	{
		get
		{
			return this.DataNascimentoField;
		}
		set
		{
			if ((this.DataNascimentoField.Equals(value) != true))
			{
				this.DataNascimentoField = value;
				this.RaisePropertyChanged("DataNascimento");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string[] Emails
	{
		get
		{
			return this.EmailsField;
		}
		set
		{
			if ((object.ReferenceEquals(this.EmailsField, value) != true))
			{
				this.EmailsField = value;
				this.RaisePropertyChanged("Emails");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int EstadoCivilCod
	{
		get
		{
			return this.EstadoCivilCodField;
		}
		set
		{
			if ((this.EstadoCivilCodField.Equals(value) != true))
			{
				this.EstadoCivilCodField = value;
				this.RaisePropertyChanged("EstadoCivilCod");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string EstadoCivilDescricao
	{
		get
		{
			return this.EstadoCivilDescricaoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.EstadoCivilDescricaoField, value) != true))
			{
				this.EstadoCivilDescricaoField = value;
				this.RaisePropertyChanged("EstadoCivilDescricao");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string EstadoSigla
	{
		get
		{
			return this.EstadoSiglaField;
		}
		set
		{
			if ((object.ReferenceEquals(this.EstadoSiglaField, value) != true))
			{
				this.EstadoSiglaField = value;
				this.RaisePropertyChanged("EstadoSigla");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Logradouro
	{
		get
		{
			return this.LogradouroField;
		}
		set
		{
			if ((object.ReferenceEquals(this.LogradouroField, value) != true))
			{
				this.LogradouroField = value;
				this.RaisePropertyChanged("Logradouro");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string NecessidadeEspecial
	{
		get
		{
			return this.NecessidadeEspecialField;
		}
		set
		{
			if ((object.ReferenceEquals(this.NecessidadeEspecialField, value) != true))
			{
				this.NecessidadeEspecialField = value;
				this.RaisePropertyChanged("NecessidadeEspecial");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string NomeMae
	{
		get
		{
			return this.NomeMaeField;
		}
		set
		{
			if ((object.ReferenceEquals(this.NomeMaeField, value) != true))
			{
				this.NomeMaeField = value;
				this.RaisePropertyChanged("NomeMae");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string NomePai
	{
		get
		{
			return this.NomePaiField;
		}
		set
		{
			if ((object.ReferenceEquals(this.NomePaiField, value) != true))
			{
				this.NomePaiField = value;
				this.RaisePropertyChanged("NomePai");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Numero
	{
		get
		{
			return this.NumeroField;
		}
		set
		{
			if ((object.ReferenceEquals(this.NumeroField, value) != true))
			{
				this.NumeroField = value;
				this.RaisePropertyChanged("Numero");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Rg
	{
		get
		{
			return this.RgField;
		}
		set
		{
			if ((object.ReferenceEquals(this.RgField, value) != true))
			{
				this.RgField = value;
				this.RaisePropertyChanged("Rg");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Sexo
	{
		get
		{
			return this.SexoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.SexoField, value) != true))
			{
				this.SexoField = value;
				this.RaisePropertyChanged("Sexo");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.TelefoneSumario[] Telefones
	{
		get
		{
			return this.TelefonesField;
		}
		set
		{
			if ((object.ReferenceEquals(this.TelefonesField, value) != true))
			{
				this.TelefonesField = value;
				this.RaisePropertyChanged("Telefones");
			}
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "TelefoneSumario", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.QueryModel.DTO.Funcionario.Tele" +
	"fones")]
[System.SerializableAttribute()]
public partial class TelefoneSumario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
{

	[System.NonSerializedAttribute()]
	private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int CodField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string ContatoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int EnderecoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string RamalField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string TelefoneField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int TerceiroField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int TipoField;

	[global::System.ComponentModel.BrowsableAttribute(false)]
	public System.Runtime.Serialization.ExtensionDataObject ExtensionData
	{
		get
		{
			return this.extensionDataField;
		}
		set
		{
			this.extensionDataField = value;
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Cod
	{
		get
		{
			return this.CodField;
		}
		set
		{
			if ((this.CodField.Equals(value) != true))
			{
				this.CodField = value;
				this.RaisePropertyChanged("Cod");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Contato
	{
		get
		{
			return this.ContatoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.ContatoField, value) != true))
			{
				this.ContatoField = value;
				this.RaisePropertyChanged("Contato");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Endereco
	{
		get
		{
			return this.EnderecoField;
		}
		set
		{
			if ((this.EnderecoField.Equals(value) != true))
			{
				this.EnderecoField = value;
				this.RaisePropertyChanged("Endereco");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Ramal
	{
		get
		{
			return this.RamalField;
		}
		set
		{
			if ((object.ReferenceEquals(this.RamalField, value) != true))
			{
				this.RamalField = value;
				this.RaisePropertyChanged("Ramal");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Telefone
	{
		get
		{
			return this.TelefoneField;
		}
		set
		{
			if ((object.ReferenceEquals(this.TelefoneField, value) != true))
			{
				this.TelefoneField = value;
				this.RaisePropertyChanged("Telefone");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Terceiro
	{
		get
		{
			return this.TerceiroField;
		}
		set
		{
			if ((this.TerceiroField.Equals(value) != true))
			{
				this.TerceiroField = value;
				this.RaisePropertyChanged("Terceiro");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Tipo
	{
		get
		{
			return this.TipoField;
		}
		set
		{
			if ((this.TipoField.Equals(value) != true))
			{
				this.TipoField = value;
				this.RaisePropertyChanged("Tipo");
			}
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "FotoFuncionario", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.QueryModel.DTO.Funcionario")]
[System.SerializableAttribute()]
public partial class FotoFuncionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
{

	[System.NonSerializedAttribute()]
	private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private byte[] FotoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumario FuncionarioField;

	[global::System.ComponentModel.BrowsableAttribute(false)]
	public System.Runtime.Serialization.ExtensionDataObject ExtensionData
	{
		get
		{
			return this.extensionDataField;
		}
		set
		{
			this.extensionDataField = value;
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public byte[] Foto
	{
		get
		{
			return this.FotoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.FotoField, value) != true))
			{
				this.FotoField = value;
				this.RaisePropertyChanged("Foto");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.FuncionarioSumario Funcionario
	{
		get
		{
			return this.FuncionarioField;
		}
		set
		{
			if ((object.ReferenceEquals(this.FuncionarioField, value) != true))
			{
				this.FuncionarioField = value;
				this.RaisePropertyChanged("Funcionario");
			}
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "FuncionarioEmail", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.QueryModel.DTO.Funcionario")]
[System.SerializableAttribute()]
public partial class FuncionarioEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
{

	[System.NonSerializedAttribute()]
	private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int CodTerceiroField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string EmailInstitucionalField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string EmailSecundarioField;

	[global::System.ComponentModel.BrowsableAttribute(false)]
	public System.Runtime.Serialization.ExtensionDataObject ExtensionData
	{
		get
		{
			return this.extensionDataField;
		}
		set
		{
			this.extensionDataField = value;
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int CodTerceiro
	{
		get
		{
			return this.CodTerceiroField;
		}
		set
		{
			if ((this.CodTerceiroField.Equals(value) != true))
			{
				this.CodTerceiroField = value;
				this.RaisePropertyChanged("CodTerceiro");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string EmailInstitucional
	{
		get
		{
			return this.EmailInstitucionalField;
		}
		set
		{
			if ((object.ReferenceEquals(this.EmailInstitucionalField, value) != true))
			{
				this.EmailInstitucionalField = value;
				this.RaisePropertyChanged("EmailInstitucional");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string EmailSecundario
	{
		get
		{
			return this.EmailSecundarioField;
		}
		set
		{
			if ((object.ReferenceEquals(this.EmailSecundarioField, value) != true))
			{
				this.EmailSecundarioField = value;
				this.RaisePropertyChanged("EmailSecundario");
			}
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name = "FuncionarioPostoDeTrabalho", Namespace = "http://schemas.datacontract.org/2004/07/MPS.ShfWs.QueryModel.DTO.Funcionario")]
[System.SerializableAttribute()]
public partial class FuncionarioPostoDeTrabalho : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
{

	[System.NonSerializedAttribute()]
	private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private System.Nullable<System.DateTime> DataFimField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private System.DateTime DataInicialField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private System.Nullable<System.DateTime> DataMovimentoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string DescricaoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int EmpresaField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private decimal EstruturadoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int FilialField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int IdField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int MatriculaField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string NomeField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private string RajDescricaoField;

	[System.Runtime.Serialization.OptionalFieldAttribute()]
	private int RajIdField;

	[global::System.ComponentModel.BrowsableAttribute(false)]
	public System.Runtime.Serialization.ExtensionDataObject ExtensionData
	{
		get
		{
			return this.extensionDataField;
		}
		set
		{
			this.extensionDataField = value;
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public System.Nullable<System.DateTime> DataFim
	{
		get
		{
			return this.DataFimField;
		}
		set
		{
			if ((this.DataFimField.Equals(value) != true))
			{
				this.DataFimField = value;
				this.RaisePropertyChanged("DataFim");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public System.DateTime DataInicial
	{
		get
		{
			return this.DataInicialField;
		}
		set
		{
			if ((this.DataInicialField.Equals(value) != true))
			{
				this.DataInicialField = value;
				this.RaisePropertyChanged("DataInicial");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public System.Nullable<System.DateTime> DataMovimento
	{
		get
		{
			return this.DataMovimentoField;
		}
		set
		{
			if ((this.DataMovimentoField.Equals(value) != true))
			{
				this.DataMovimentoField = value;
				this.RaisePropertyChanged("DataMovimento");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Descricao
	{
		get
		{
			return this.DescricaoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.DescricaoField, value) != true))
			{
				this.DescricaoField = value;
				this.RaisePropertyChanged("Descricao");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Empresa
	{
		get
		{
			return this.EmpresaField;
		}
		set
		{
			if ((this.EmpresaField.Equals(value) != true))
			{
				this.EmpresaField = value;
				this.RaisePropertyChanged("Empresa");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public decimal Estruturado
	{
		get
		{
			return this.EstruturadoField;
		}
		set
		{
			if ((this.EstruturadoField.Equals(value) != true))
			{
				this.EstruturadoField = value;
				this.RaisePropertyChanged("Estruturado");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Filial
	{
		get
		{
			return this.FilialField;
		}
		set
		{
			if ((this.FilialField.Equals(value) != true))
			{
				this.FilialField = value;
				this.RaisePropertyChanged("Filial");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Id
	{
		get
		{
			return this.IdField;
		}
		set
		{
			if ((this.IdField.Equals(value) != true))
			{
				this.IdField = value;
				this.RaisePropertyChanged("Id");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int Matricula
	{
		get
		{
			return this.MatriculaField;
		}
		set
		{
			if ((this.MatriculaField.Equals(value) != true))
			{
				this.MatriculaField = value;
				this.RaisePropertyChanged("Matricula");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string Nome
	{
		get
		{
			return this.NomeField;
		}
		set
		{
			if ((object.ReferenceEquals(this.NomeField, value) != true))
			{
				this.NomeField = value;
				this.RaisePropertyChanged("Nome");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public string RajDescricao
	{
		get
		{
			return this.RajDescricaoField;
		}
		set
		{
			if ((object.ReferenceEquals(this.RajDescricaoField, value) != true))
			{
				this.RajDescricaoField = value;
				this.RaisePropertyChanged("RajDescricao");
			}
		}
	}

	[System.Runtime.Serialization.DataMemberAttribute()]
	public int RajId
	{
		get
		{
			return this.RajIdField;
		}
		set
		{
			if ((this.RajIdField.Equals(value) != true))
			{
				this.RajIdField = value;
				this.RaisePropertyChanged("RajId");
			}
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "FuncionarioService.IFuncionarioService")]
public interface IFuncionarioService
{

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/PesquisarFuncionariosNome", ReplyAction = "http://tempuri.org/IFuncionarioService/PesquisarFuncionariosNomeResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioAutoCompletJCxYsfas PesquisarFuncionariosNome(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string nome);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/PesquisarFuncionariosNome", ReplyAction = "http://tempuri.org/IFuncionarioService/PesquisarFuncionariosNomeResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioAutoCompletJCxYsfas> PesquisarFuncionariosNomeAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string nome);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterPorMatricula", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterPorMatriculaResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioJCxYsfas ObterPorMatricula(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterPorMatricula", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterPorMatriculaResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioJCxYsfas> ObterPorMatriculaAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarPorListaMatricula", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarPorListaMatriculaResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas SelecionarPorListaMatricula(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, int[] listaMatricula);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarPorListaMatricula", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarPorListaMatriculaResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas> SelecionarPorListaMatriculaAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, int[] listaMatricula);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarPorNome", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarPorNomeResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas SelecionarPorNome(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string nome);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarPorNome", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarPorNomeResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas> SelecionarPorNomeAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string nome);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterFotoPorMatricula", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterFotoPorMatriculaResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFotoFuncionarioJCxYsfas ObterFotoPorMatricula(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterFotoPorMatricula", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterFotoPorMatriculaResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFotoFuncionarioJCxYsfas> ObterFotoPorMatriculaAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterEmailPorMatricula", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterEmailPorMatriculaResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioEmailJCxYsfas ObterEmailPorMatricula(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterEmailPorMatricula", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterEmailPorMatriculaResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioEmailJCxYsfas> ObterEmailPorMatriculaAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarPorCpf", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarPorCpfResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas SelecionarPorCpf(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, long cpf);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarPorCpf", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarPorCpfResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas> SelecionarPorCpfAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, long cpf);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarFuncionariosPorLotacaoCod", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarFuncionariosPorLotacaoCodRespons" +
		"e")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas SelecionarFuncionariosPorLotacaoCod(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, int lotacaoCod);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarFuncionariosPorLotacaoCod", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarFuncionariosPorLotacaoCodRespons" +
		"e")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas> SelecionarFuncionariosPorLotacaoCodAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, int lotacaoCod);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterPorMatriculaCompleto", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterPorMatriculaCompletoResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioCompletoJCxYsfas ObterPorMatriculaCompleto(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterPorMatriculaCompleto", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterPorMatriculaCompletoResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioCompletoJCxYsfas> ObterPorMatriculaCompletoAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/AlterarEmailSecundario", ReplyAction = "http://tempuri.org/IFuncionarioService/AlterarEmailSecundarioResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno AlterarEmailSecundario(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string codTerceiro, string emailSecundario);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/AlterarEmailSecundario", ReplyAction = "http://tempuri.org/IFuncionarioService/AlterarEmailSecundarioResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno> AlterarEmailSecundarioAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string codTerceiro, string emailSecundario);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterFuncionarioPostoDeTrabalho", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterFuncionarioPostoDeTrabalhoResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioPostoDeTrabalhoJCxYsfas ObterFuncionarioPostoDeTrabalho(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, System.DateTime dataReferencia);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/ObterFuncionarioPostoDeTrabalho", ReplyAction = "http://tempuri.org/IFuncionarioService/ObterFuncionarioPostoDeTrabalhoResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioPostoDeTrabalhoJCxYsfas> ObterFuncionarioPostoDeTrabalhoAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, System.DateTime dataReferencia);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarFuncionaroPostoDeTrabalhoPorPeri" +
		"odo", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarFuncionaroPostoDeTrabalhoPorPeri" +
		"odoResponse")]
	MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioPostoDeTrabalhoJCxYsfas SelecionarFuncionaroPostoDeTrabalhoPorPeriodo(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, System.DateTime dataInicial, System.DateTime dataFinal);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFuncionarioService/SelecionarFuncionaroPostoDeTrabalhoPorPeri" +
		"odo", ReplyAction = "http://tempuri.org/IFuncionarioService/SelecionarFuncionaroPostoDeTrabalhoPorPeri" +
		"odoResponse")]
	System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioPostoDeTrabalhoJCxYsfas> SelecionarFuncionaroPostoDeTrabalhoPorPeriodoAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, System.DateTime dataInicial, System.DateTime dataFinal);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFuncionarioServiceChannel : MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.IFuncionarioService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FuncionarioServiceClient : System.ServiceModel.ClientBase<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.IFuncionarioService>, MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.IFuncionarioService
{

	public FuncionarioServiceClient()
	{
	}

	public FuncionarioServiceClient(string endpointConfigurationName) :
			base(endpointConfigurationName)
	{
	}

	public FuncionarioServiceClient(string endpointConfigurationName, string remoteAddress) :
			base(endpointConfigurationName, remoteAddress)
	{
	}

	public FuncionarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
			base(endpointConfigurationName, remoteAddress)
	{
	}

	public FuncionarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
			base(binding, remoteAddress)
	{
	}

	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioAutoCompletJCxYsfas PesquisarFuncionariosNome(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string nome)
	{
		return base.Channel.PesquisarFuncionariosNome(baseEntrada, nome);
	}

	public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioAutoCompletJCxYsfas> PesquisarFuncionariosNomeAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string nome)
	{
		return base.Channel.PesquisarFuncionariosNomeAsync(baseEntrada, nome);
	}

	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioJCxYsfas ObterPorMatricula(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada)
	{
		return base.Channel.ObterPorMatricula(baseEntrada);
	}

	public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioJCxYsfas> ObterPorMatriculaAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada)
	{
		return base.Channel.ObterPorMatriculaAsync(baseEntrada);
	}

	public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas SelecionarPorListaMatricula(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, int[] listaMatricula)
	{
		return base.Channel.SelecionarPorListaMatricula(baseEntrada, listaMatricula);
	}

	public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas> SelecionarPorListaMatriculaAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, int[] listaMatricula) {
            return base.Channel.SelecionarPorListaMatriculaAsync(baseEntrada, listaMatricula);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas SelecionarPorNome(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string nome) {
            return base.Channel.SelecionarPorNome(baseEntrada, nome);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas> SelecionarPorNomeAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string nome) {
            return base.Channel.SelecionarPorNomeAsync(baseEntrada, nome);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFotoFuncionarioJCxYsfas ObterFotoPorMatricula(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada) {
            return base.Channel.ObterFotoPorMatricula(baseEntrada);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFotoFuncionarioJCxYsfas> ObterFotoPorMatriculaAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada) {
            return base.Channel.ObterFotoPorMatriculaAsync(baseEntrada);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioEmailJCxYsfas ObterEmailPorMatricula(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada) {
            return base.Channel.ObterEmailPorMatricula(baseEntrada);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioEmailJCxYsfas> ObterEmailPorMatriculaAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada) {
            return base.Channel.ObterEmailPorMatriculaAsync(baseEntrada);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas SelecionarPorCpf(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, long cpf) {
            return base.Channel.SelecionarPorCpf(baseEntrada, cpf);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas> SelecionarPorCpfAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, long cpf) {
            return base.Channel.SelecionarPorCpfAsync(baseEntrada, cpf);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas SelecionarFuncionariosPorLotacaoCod(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, int lotacaoCod) {
            return base.Channel.SelecionarFuncionariosPorLotacaoCod(baseEntrada, lotacaoCod);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioSumarioJCxYsfas> SelecionarFuncionariosPorLotacaoCodAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, int lotacaoCod) {
            return base.Channel.SelecionarFuncionariosPorLotacaoCodAsync(baseEntrada, lotacaoCod);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioCompletoJCxYsfas ObterPorMatriculaCompleto(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada) {
            return base.Channel.ObterPorMatriculaCompleto(baseEntrada);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioSumarioCompletoJCxYsfas> ObterPorMatriculaCompletoAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada) {
            return base.Channel.ObterPorMatriculaCompletoAsync(baseEntrada);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno AlterarEmailSecundario(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string codTerceiro, string emailSecundario) {
            return base.Channel.AlterarEmailSecundario(baseEntrada, codTerceiro, emailSecundario);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetorno> AlterarEmailSecundarioAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, string codTerceiro, string emailSecundario) {
            return base.Channel.AlterarEmailSecundarioAsync(baseEntrada, codTerceiro, emailSecundario);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioPostoDeTrabalhoJCxYsfas ObterFuncionarioPostoDeTrabalho(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, System.DateTime dataReferencia) {
            return base.Channel.ObterFuncionarioPostoDeTrabalho(baseEntrada, dataReferencia);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoOfFuncionarioPostoDeTrabalhoJCxYsfas> ObterFuncionarioPostoDeTrabalhoAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, System.DateTime dataReferencia) {
            return base.Channel.ObterFuncionarioPostoDeTrabalhoAsync(baseEntrada, dataReferencia);
        }
        
        public MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioPostoDeTrabalhoJCxYsfas SelecionarFuncionaroPostoDeTrabalhoPorPeriodo(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, System.DateTime dataInicial, System.DateTime dataFinal) {
            return base.Channel.SelecionarFuncionaroPostoDeTrabalhoPorPeriodo(baseEntrada, dataInicial, dataFinal);
        }
        
        public System.Threading.Tasks.Task<MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseRetornoObjetoListOfFuncionarioPostoDeTrabalhoJCxYsfas> SelecionarFuncionaroPostoDeTrabalhoPorPeriodoAsync(MPS.MPSPadraoArquitetura.Aplicacao.FuncionarioService.BaseEntrada baseEntrada, System.DateTime dataInicial, System.DateTime dataFinal) {
            return base.Channel.SelecionarFuncionaroPostoDeTrabalhoPorPeriodoAsync(baseEntrada, dataInicial, dataFinal);
        }
    }
}
